/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPlanoRouteImport } from './routes/app.plano'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPagamentosRouteImport } from './routes/app.pagamentos'
import { Route as AppBeneficiariosRouteImport } from './routes/app.beneficiarios'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanoRoute = AppPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiariosRoute = AppBeneficiariosRouteImport.update({
  id: '/beneficiarios',
  path: '/beneficiarios',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/beneficiarios': typeof AppBeneficiariosRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/beneficiarios': typeof AppBeneficiariosRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/beneficiarios': typeof AppBeneficiariosRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/beneficiarios'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/plano'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/beneficiarios'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/plano'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/beneficiarios'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/plano'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plano': {
      id: '/app/plano'
      path: '/plano'
      fullPath: '/app/plano'
      preLoaderRoute: typeof AppPlanoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamentos': {
      id: '/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/beneficiarios': {
      id: '/app/beneficiarios'
      path: '/beneficiarios'
      fullPath: '/app/beneficiarios'
      preLoaderRoute: typeof AppBeneficiariosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBeneficiariosRoute: typeof AppBeneficiariosRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanoRoute: typeof AppPlanoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeneficiariosRoute: AppBeneficiariosRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanoRoute: AppPlanoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
